src/objects/Answer__c.object
<CustomObject>
    <description>These are the answers associated with a question.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <description>The answer to display to the exam taker.</description>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Correct__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this answer is a correct answer.</description>
        <label>Correct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>The sequence the answer should appear within the question.</description>
        <label>Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>The related question that the answer belongs to.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating if the exam taker has chosen this answer.</description>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Examination__c.object
<CustomObject>
    <description>An examination is essentially an instance of a test for an exam taker.  When a new examination is created, it contains a copy of all the questions from the test form that make up the test.  Examinations may be performed in practice mode.</description>
    <fields>
        <fullName>Examination_Status__c</fullName>
        <description>The examination status indicates whether an examination is New, In Progress, or Completed.</description>
        <label>Examination Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Examination_Taker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The examination taker field indicates the person taking the examination.</description>
        <label>Examination Taker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The test form field indicates the test form that this examination was created from.</description>
        <label>Test Form</label>
        <referenceTo>Test_Form__c</referenceTo>
        <relationshipLabel>Examinations</relationshipLabel>
        <relationshipName>Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <label>Examination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>A question may be related to either a test form or an examination.  Test form questions are used as templates when creating examination questions.</description>
    <fields>
        <fullName>Correct__c</fullName>
        <description>Checks to see if the number of correctly selected answers equals the number of correct answers.</description>
        <formula>IF(Number_Correctly_Selected__c == Number_of_Correct_Answers__c,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Correct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The examination field indicates the examination that this question belongs to.</description>
        <label>Examination</label>
        <referenceTo>Examination__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mark_For_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to indicate that the exam taker wishes to review the question.</description>
        <label>Mark For Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Correctly_Selected__c</fullName>
        <description>Total number of correctly selected answers.</description>
        <label>Number Correctly Selected</label>
        <summarizedField>Answer__c.Answer_is_Correct__c</summarizedField>
        <summaryFilterItems>
            <field>Answer__c.Selected__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Question__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Correct_Answers__c</fullName>
        <description>Total number of correct answers.</description>
        <label>Number of Correct Answers</label>
        <summaryFilterItems>
            <field>Answer__c.Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Question__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>The question number indicates the order in which to display the questions in an examination.  This field is not used for exam template questions.</description>
        <label>Question Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>This is the body which makes up a question.</description>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Test_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The test form field indicates the test form that this question belongs to.</description>
        <label>Test Form</label>
        <referenceTo>Test_Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Test_Form__c.object
<CustomObject>
    <description>The test form is used to store information about a test.  It contains a description as well as summary information.  Test forms are created and managed by an exam administrator.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Exam Templates, and therefore Examinations are specific to the Accounts that they are for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Exam_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Status__c</fullName>
        <description>The test status field indicates whether a test is Draft, Open (available to take), Closed, or Obsolete.</description>
        <label>Test Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Test Form</label>
    <nameField>
        <label>Test Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>This field is used to store the ID of the Account that a Test Taker belongs to. Test Takers can only take Examinations that are available for their Account.</description>
        <label>Account ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestUtilities.cls
/**
 * Test Utilities class for common test methods and data creation
 */
@isTest
public with sharing class TestUtilities {
    
    //Control properties
    private static final Integer maxChars = 15;
    public static final Integer numberOfTakers = 10;
    public static final Integer numberOfAccounts = 1;
    public static final Integer numberOfTestForms = 1;
    public static final Integer numberOfExaminations = 2;
    public static final Integer numberOfQuestions = 30;
    public static final Integer numberOfAnswers = 5;
    public static final Integer numberOfCorrectAnswers = 2;
    public static final String draftStatus = 'Draft';
    
    //Get Random strings to avoid conflicts
    public static String getRandomString(Integer max) {
        String randomString = EncodingUtil.base64Encode(crypto.generateAesKey(128)).substring(1,max).toUpperCase();
        return randomString;
    }
    
    //Create a list of accounts
    public static List<Account> createAccounts(Integer quantity) {
        
        List<Account> returnAccounts = new List<Account>();
        Account tempAccount = new Account();
        for (Integer i = 0;i< quantity; i++) {
            tempAccount = new Account(name=getRandomString(maxChars));
            returnAccounts.add(tempAccount);
        }
        return returnAccounts;
    }
    
    //Create a list of test forms
    public static List<Test_Form__c> createTestForms(Integer quantity, Id AccountId, String Status) {
        
        List<Test_Form__c> returnTestForms = new List<Test_Form__c>();
        Test_Form__c tempTestForm = new Test_Form__c();
        for (Integer i = 0;i< quantity; i++) {
            tempTestForm = new Test_Form__c(name=getRandomString(maxChars), Account__c = AccountId, Test_Status__c = Status);
            returnTestForms.add(tempTestForm);
        }
        return returnTestForms;
    }
    
    //Create a list of examinations
    public static List<Examination__c> createExaminations(Integer quantity, Id TestFormId, Id TakerId, String Status) {
        
        List<Examination__c> returnExaminations = new List<Examination__c>();
        Examination__c tempExamination = new Examination__c();
        for (Integer i = 0;i< quantity; i++) {
            tempExamination = new Examination__c(name=getRandomString(maxChars), Test_Form__c = TestFormId, Examination_Status__c = Status, Examination_Taker__c = TakerId);
            returnExaminations.add(tempExamination);
        }
        return returnExaminations;
    }
    
    //Create a list of questions
    public static List<Question__c> createQuestions(Integer Quantity, Id parentId, Boolean isTestForm) {
        List<Question__c> returnQuestions = new List<Question__c>();
        Question__c tempQuestion = new Question__c();
        for (Integer i = 0;i< quantity; i++) {
            if (isTestForm) {
                tempQuestion = new Question__c(name=getRandomString(maxChars), Test_Form__c = parentId, Question_Number__c = i+1, Question__c = getRandomString(maxChars));
            }
            else {
                tempQuestion = new Question__c(name=getRandomString(maxChars), Examination__c = parentId, Question_Number__c = i+1, Question__c = getRandomString(maxChars));
            }
            returnQuestions.add(tempQuestion);
        }
        
        return returnQuestions;
    }
    
    //Create a list of answers
    public static List<Answer__c> createAnswers(Integer Quantity, Id QuestionId) {
        List<Answer__c> returnAnswers = new List<Answer__c>();
        Answer__c tempAnswer = new Answer__c();
        for (Integer i = 0;i< quantity; i++) {
            tempAnswer = new Answer__c(name=getRandomString(maxChars), Question__c = QuestionId, Number__c = i+1, Answer__c = getRandomString(maxChars));
            returnAnswers.add(tempAnswer);
        }
        
        return returnAnswers;
    }
    
    //Create a list of Exam Administrators
    public static List<User> getExamAdminUsers(Integer quantity) {
        List<User> returnUsers = new List<User>();
        Map<String,ID> profiles = new Map<String,String>();
        List<Profile> ps = [select id, name from Profile where name = 'Custom: Exam Administrator'];
        for(Profile p : ps){
            profiles.put(p.name, p.id);
        }
        
        User admin = new User();
        
        for (Integer i = 0;i< quantity; i++) {
            admin = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                EmailEncodingKey='UTF-8', LastName=getRandomString(maxChars), LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = profiles.get('Custom: Exam Administrator'), 
                TimeZoneSidKey='America/Los_Angeles', UserName=getRandomString(maxChars) + '@cert501.ivan');
            returnUsers.add(admin);
        }
        
        return returnUsers;
    }
    
    //Create a list of Exam Takers
    public static List<User> getExamTakerUsers(Integer quantity) {
        List<User> returnUsers = new List<User>();
        Map<String,ID> profiles = new Map<String,String>();
        List<Profile> ps = [select id, name from Profile where name = 'Custom: Exam Taker'];
        for(Profile p : ps){
            profiles.put(p.name, p.id);
        }
        User taker = new User();
        
        for (Integer i = 0;i< quantity; i++) {
            taker = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                EmailEncodingKey='UTF-8', LastName=getRandomString(maxChars), LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = profiles.get('Custom: Exam Taker'), 
                TimeZoneSidKey='America/Los_Angeles', UserName=getRandomString(maxChars) + '@cert501.ivan');
            returnUsers.add(taker);
        }
        return returnUsers;
    }
    
    //Create a list of exam takers with a specific account Id
    public static List<User> getExamTakerUsers(Integer quantity, String AccountId) {
        List<User> returnUsers = new List<User>();
        Map<String,ID> profiles = new Map<String,String>();
        List<Profile> ps = [select id, name from Profile where name = 'Custom: Exam Taker'];
        for(Profile p : ps){
            profiles.put(p.name, p.id);
        }
        User taker = new User();
        
        for (Integer i = 0;i< quantity; i++) {
            taker = new User(Account_ID__c = AccountId,Alias = 'standt', Email='standarduser@testorg.com', 
                EmailEncodingKey='UTF-8', LastName=getRandomString(maxChars), LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = profiles.get('Custom: Exam Taker'), 
                TimeZoneSidKey='America/Los_Angeles', UserName=getRandomString(maxChars) + '@cert501.ivan');
            returnUsers.add(taker);
        }
        return returnUsers;
    }
    
    //Create a set of bulk data for testing the User Loads
    public static List<User> createBulkData (String fakeAccount) {
        Integer numAcct = TestUtilities.numberOfAccounts;
        Integer numTests = TestUtilities.numberOfTestForms;
        Integer numUsers = TestUtilities.numberOfTakers;

        List<Account> accounts = TestUtilities.createAccounts(numAcct);
        insert accounts;
        List<Test_Form__c> testForms = new List<Test_Form__c>();
        List<Question__c> questions = new List<Question__c>();
        List<User> users = new List<User>();
        
        for (Account acc : accounts) {
            testForms.addAll(TestUtilities.createTestForms(numTests, acc.Id, 'Open'));
            if (fakeAccount == null)
                users.addAll(getExamTakerUsers(numUsers,acc.Id));
            else
                users.addAll(getExamTakerUsers(numUsers,fakeAccount));
        }
        
        insert testForms;
        
        for(Test_Form__c form : testForms) {
            //questions = new List<Question__c>();
            questions.addAll(TestUtilities.createQuestions(TestUtilities.numberOfQuestions, form.Id, true));
        }
        
        insert questions;
        
        List<Answer__c> answers = new List<Answer__c>();
        List<Answer__c> tempAnswers = new List<Answer__c>();
        Integer numberSelected = TestUtilities.numberOfCorrectAnswers;
        
        for (Question__c question : questions) {
            tempAnswers = TestUtilities.createAnswers(TestUtilities.numberOfAnswers, question.Id);
            for (Integer i = 0; i<tempAnswers.size(); i++) {
                if (i < numberSelected) {
                    tempAnswers[i].Selected__c = true;
                    tempAnswers[i].Correct__c = true;
                }
            }
            answers.addAll(tempAnswers);
        }
        insert answers;
        
        return users;
    }
    
    //Create a Question Wrapper for a correct question
    public static QuestionAnswerWrapper createCorrectQuestion() {
        List<Account> accounts = TestUtilities.createAccounts(1);
        insert accounts;
        List<Test_Form__c> testForms = TestUtilities.createTestForms(1, accounts[0].Id, 'Draft');
        insert testforms;
        List<Question__c> questions = TestUtilities.createQuestions(1, testforms[0].Id, true);
        insert questions;
        
        List<Answer__c> answers = new List<Answer__c>();
        List<Answer__c> tempAnswers = new List<Answer__c>();
        Integer numberSelected = TestUtilities.numberOfCorrectAnswers; 
        for (Question__c question : questions) {
            tempAnswers = TestUtilities.createAnswers(TestUtilities.numberOfAnswers, question.Id);
            for (Integer i = 0; i<tempAnswers.size(); i++) {
                if (i < numberSelected) {
                    tempAnswers[i].Selected__c = true;
                    tempAnswers[i].Correct__c = true;
                }
            }
            answers.addAll(tempAnswers);
        }
        insert answers;
        
        questions[0] = [Select 
                        Question__c, 
                        Question_Number__c,
                        Number_of_Correct_Answers__c,
                        Number_Correctly_Selected__c,
                        Mark_For_Review__c,
                        (Select
                            Number__c,
                            Selected__c,
                            Answer__c
                         from Answers__r
                         order by Number__c asc
                        )
                     from Question__c
                     where Id = :questions[0].Id limit 1];
        return new QuestionAnswerWrapper(questions[0]);
    }
    
    //Create a Question Wrapper for a wrong question
    public static QuestionAnswerWrapper createWrongQuestion() {
        List<Account> accounts = TestUtilities.createAccounts(1);
        insert accounts;
        List<Test_Form__c> testForms = TestUtilities.createTestForms(1, accounts[0].Id, 'Draft');
        insert testforms;
        List<Question__c> questions = TestUtilities.createQuestions(1, testforms[0].Id, true);
        insert questions;
        
        List<Answer__c> answers = new List<Answer__c>();
        List<Answer__c> tempAnswers = new List<Answer__c>();
        Integer numberSelected = TestUtilities.numberOfCorrectAnswers; 
        for (Question__c question : questions) {
            tempAnswers = TestUtilities.createAnswers(TestUtilities.numberOfAnswers, question.Id);
            for (Integer i = 0; i<tempAnswers.size(); i++) {
                if (i < numberSelected) {
                    tempAnswers[i].Selected__c = false;
                    tempAnswers[i].Correct__c = true;
                }
                else
                    tempAnswers[i].Selected__c = true;
            }
            answers.addAll(tempAnswers);
        }
        insert answers;
        
        questions[0] = [Select 
                        Question__c, 
                        Question_Number__c,
                        Number_of_Correct_Answers__c,
                        Number_Correctly_Selected__c,
                        Mark_For_Review__c,
                        (Select
                            Number__c,
                            Selected__c,
                            Answer__c
                         from Answers__r
                         order by Number__c asc
                        )
                     from Question__c
                     where Id = :questions[0].Id limit 1];
                                     
        return new QuestionAnswerWrapper(questions[0]);
    }
    
    //Create an individual examination that has been passed or not, depending on the parameter
    public static Examination__c createExamination(User taker, Boolean passed) {
        List<Account> accounts = TestUtilities.createAccounts(1);
        insert accounts;
        List<Test_Form__c> testForms = TestUtilities.createTestForms(1, accounts[0].Id, 'Draft');
        insert testforms;
        List<Examination__c> examinations = TestUtilities.createExaminations(1, testForms[0].Id, taker.Id, 'In Progress');
        insert examinations;
        List<Question__c> questions = TestUtilities.createQuestions(TestUtilities.numberOfQuestions, examinations[0].Id, false);
        insert questions;
        
        List<Answer__c> answers = new List<Answer__c>();
        List<Answer__c> tempAnswers = new List<Answer__c>();
        Integer numberSelected = TestUtilities.numberOfCorrectAnswers; 
        for (Question__c question : questions) {
            tempAnswers = TestUtilities.createAnswers(TestUtilities.numberOfAnswers, question.Id);
            for (Integer i = 0; i<tempAnswers.size(); i++) {
                if (passed) {
                    if (i < numberSelected) {
                        tempAnswers[i].Selected__c = true;
                        tempAnswers[i].Correct__c = true;
                    }
                }
                else {
                    if (i < numberSelected) {
                        tempAnswers[i].Selected__c = false;
                        tempAnswers[i].Correct__c = true;
                    }
                    else
                        tempAnswers[i].Selected__c = true;
                }
            }
            answers.addAll(tempAnswers);
        }
        insert answers;
        
        return examinations[0];
    }
    
    //Create an individual Test Form that has been passed or not, depending on the parameter
    public static Test_Form__c createTestForm(Boolean passed) {
        List<Account> accounts = TestUtilities.createAccounts(1);
        insert accounts;
        List<Test_Form__c> testForms = TestUtilities.createTestForms(1, accounts[0].Id, 'Draft');
        insert testforms;
        List<Question__c> questions = TestUtilities.createQuestions(TestUtilities.numberOfQuestions, testForms[0].Id, true);
        insert questions;
        
        List<Answer__c> answers = new List<Answer__c>();
        List<Answer__c> tempAnswers = new List<Answer__c>();
        Integer numberSelected = TestUtilities.numberOfCorrectAnswers; 
        for (Question__c question : questions) {
            tempAnswers = TestUtilities.createAnswers(TestUtilities.numberOfAnswers, question.Id);
            for (Integer i = 0; i<tempAnswers.size(); i++) {
                if (passed) {
                    if (i < numberSelected) {
                        tempAnswers[i].Selected__c = true;
                        tempAnswers[i].Correct__c = true;
                    }
                }
                else {
                    if (i < numberSelected) {
                        tempAnswers[i].Selected__c = false;
                        tempAnswers[i].Correct__c = true;
                    }
                    else
                        tempAnswers[i].Selected__c = true;
                }
            }
            answers.addAll(tempAnswers);
        }
        insert answers;
        return testForms[0];
    }
}