src/objects/Answer__c.object
<CustomObject>
    <description>These are the answers associated with a question.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <description>The answer to display to the exam taker.</description>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>The sequence the answer should appear within the question.</description>
        <label>Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>The related question that the answer belongs to.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating if the exam taker has chosen this answer.</description>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ErrorLog__c.object
<CustomObject>
    <description>Object used to store unexpected errors, while not showing them to the end users.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ErrorLog</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ErrorLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>A question may be related to either a test form or an examination.  Test form questions are used as templates when creating examination questions.</description>
    <fields>
        <fullName>Mark_For_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to indicate that the exam taker wishes to review the question.</description>
        <label>Mark For Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Correctly_Selected__c</fullName>
        <description>Total number of correctly selected answers.</description>
        <label>Number Correctly Selected</label>
        <summarizedField>Answer__c.Answer_is_Correct__c</summarizedField>
        <summaryFilterItems>
            <field>Answer__c.Selected__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Question__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Correct_Answers__c</fullName>
        <description>Total number of correct answers.</description>
        <label>Number of Correct Answers</label>
        <summaryFilterItems>
            <field>Answer__c.Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Question__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>The question number indicates the order in which to display the questions in an examination.  This field is not used for exam template questions.</description>
        <label>Question Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>This is the body which makes up a question.</description>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Test_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The test form field indicates the test form that this question belongs to.</description>
        <label>Test Form</label>
        <referenceTo>Test_Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Test_Form__c.object
<CustomObject>
    <description>The test form is used to store information about a test.  It contains a description as well as summary information.  Test forms are created and managed by an exam administrator.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>The description contains an extended description of the exam name including pre-requisites and the intended exam taker.</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Test Form</label>
    <nameField>
        <label>Test Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestDraftController.cls
/*
 * Class that controls the behaviour of the TestDraftPage, this allows administrator users to
 * take Test Forms in Draft Status to simulate how the examinations are going to be.
 * I used a different controller and page for Examinations and Test Forms in order to allow tailoring
 * of the experience of Takers and Administrators, having differences regarding the Status management, the question 
 * and answer numbers, giving the possibility to close the window at any time, and any other future different behaviour needed
 * Being that so, I created a Commons class that has the common methods used by both of the controllers and that provide the main
 * functionalities of a test, providing ability to reuse for other different test experiences.  
 */
public without sharing class TestDraftController {

	//Properties for the page functioning
	private Test_Form__c exam;
	public String draftStatus {
		get {
			return 'Draft';
		}
	}
	
	//Control the actual question
	public Integer actualQuestion {
		get {
			if (actualQuestion == null)
				actualQuestion = 1;
			return actualQuestion;
		}
		set;
	}
	
	//Labels for progress and number of correct answers
	public String questionLabel{
		get {
			return String.format(System.Label.QuestionLabel, new List<String>{String.valueOf(actualQuestion), String.valueOf(questionCount)});
		}
	}
	public String selectLabel{
		get {
			return String.format(System.Label.SelectLabel, new List<String>{String.valueOf(questionWrapper.question.Number_of_Correct_Answers__c)});
		}
	}
	
	//List of Question and Answers wrappers to manage simulation progress
	public List<QuestionAnswerWrapper> questionAnswerWrapperList {
		get {
			if (questionAnswerWrapperList == null)
				questionAnswerWrapperList = new List<QuestionAnswerWrapper>();
			return questionAnswerWrapperList;
		}
		set;
	}
	//Question Wrapper object obtained by getting the actualQuestion index from questionAnswerWrapperList
	public QuestionAnswerWrapper questionWrapper {
		get {
			if (questionCount >= actualQuestion && actualQuestion > 0) {
				questionWrapper = questionAnswerWrapperList[actualQuestion - 1];
			}
			return questionWrapper;
		}
		set;
	}
	//Total of questions
	public Integer questionCount {get;set;}
	public Boolean isEmpty {get;set;}
	public Boolean isReview {
		get {
			if (isReview == null)
				isReview = false;
			return isReview;
		}
		set;
	}
	public Boolean isDone {get;set;}
	
	public String result {get;set;}
	
	//Constructor of the class
	public TestDraftController (ApexPages.StandardController stdController) {
		
		exam = (Test_Form__c) stdController.getRecord();

		List<Question__c> questions = [Select 
						Question__c, 
						Question_Number__c,
						Number_of_Correct_Answers__c,
						Number_Correctly_Selected__c,
						Mark_For_Review__c,
						(Select
							Number__c,
							Selected__c,
							Answer__c
						 from Answers__r
						 order by Number__c asc
						)
					 from Question__c
					 where Test_Form__c = :exam.Id
					 order by Question_Number__c asc
					];
		
		if (questions.size() == 0)
			isEmpty = true;
		else {
			questionAnswerWrapperList = Commons.fillWrapperList(questions);
			questionCount = questionAnswerWrapperList.size();
		}
	}
	
	//Next functionality
	public void next() {
		try {
			if (questionWrapper == null)
				throw new Commons.InvalidQuestionException(System.Label.InvalidQuestion);
			actualQuestion = Commons.next(questionWrapper, actualQuestion);
		}
		catch (Commons.InvalidNumberSelectedException ex) {
			ApexPages.addMessages(ex);
		}
		catch (Exception exc) {
			ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.FATAL,System.Label.FatalError);
			ApexPages.addMessage(message);
			
			//Create error log for the administrator to be able to know what happened
			ErrorLog__c errorLog = new ErrorLog__c(Object__c = Schema.SObjectType.Test_Form__c.getName(), Description__c = exc.getMessage() + ' -- Stack: ' + exc.getStackTraceString());
			insert errorLog;
		}
	}
	
	//Previous functionality
	public void previous() {
		try {
			if (questionWrapper == null)
				throw new Commons.InvalidQuestionException(System.Label.InvalidQuestion);
			actualQuestion = Commons.previous(questionWrapper, actualQuestion);
		}
		catch (Commons.InvalidNumberSelectedException ex) {
			ApexPages.addMessages(ex);
		}
		catch (Exception exc) {
			ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.FATAL,System.Label.FatalError);
			ApexPages.addMessage(message);
			
			//Create error log for the administrator to be able to know what happened
			ErrorLog__c errorLog = new ErrorLog__c(Object__c = Schema.SObjectType.Test_Form__c.getName(), Description__c = exc.getMessage() + ' -- Stack: ' + exc.getStackTraceString());
			insert errorLog;
		}
	}
	
	//Review functionality
	public void review() {
		try {
			if (questionWrapper == null)
				throw new Commons.InvalidQuestionException(System.Label.InvalidQuestion);
			isReview = Commons.review(questionWrapper);
		}
		catch (Commons.InvalidNumberSelectedException ex) {
			ApexPages.addMessages(ex);
		}
		catch (Exception exc) {
			ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.FATAL,System.Label.FatalError);
			ApexPages.addMessage(message);
			
			//Create error log for the administrator to be able to know what happened
			ErrorLog__c errorLog = new ErrorLog__c(Object__c = Schema.SObjectType.Test_Form__c.getName(), Description__c = exc.getMessage() + ' -- Stack: ' + exc.getStackTraceString());
			insert errorLog;
		}
	}
	
	//Exit review and go to question
	public void goToQuestion() {
		isReview = false;
	}
	
	//Finish and calculate score if in review screen, go to review if not
	public void finish () {
		
		if (isReview) {
			isDone = true;
			
			Commons.resultClass resultClass = Commons.calculateResult(exam);
			if (resultClass.pass) {
				result = String.format(System.Label.PassLabel, new List<String>{String.valueOf(resultClass.correctAnswers), String.valueOf(questionCount)});
			}
			else {
				result = String.format(System.Label.FailLabel, new List<String>{String.valueOf(resultClass.correctAnswers), String.valueOf(questionCount)});
			}
		}
		else
			review();
	}
}