src/objects/Answer__c.object
<CustomObject>
    <description>These are the answers associated with a question.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <description>The answer to display to the exam taker.</description>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <description>The sequence the answer should appear within the question.</description>
        <label>Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>The related question that the answer belongs to.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating if the exam taker has chosen this answer.</description>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Examination__c.object
<CustomObject>
    <description>An examination is essentially an instance of a test for an exam taker.  When a new examination is created, it contains a copy of all the questions from the test form that make up the test.  Examinations may be performed in practice mode.</description>
    <fields>
        <fullName>Examination_Status__c</fullName>
        <description>The examination status indicates whether an examination is New, In Progress, or Completed.</description>
        <label>Examination Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <label>Examination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>A question may be related to either a test form or an examination.  Test form questions are used as templates when creating examination questions.</description>
    <fields>
        <fullName>Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The examination field indicates the examination that this question belongs to.</description>
        <label>Examination</label>
        <referenceTo>Examination__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mark_For_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to indicate that the exam taker wishes to review the question.</description>
        <label>Mark For Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Correctly_Selected__c</fullName>
        <description>Total number of correctly selected answers.</description>
        <label>Number Correctly Selected</label>
        <summarizedField>Answer__c.Answer_is_Correct__c</summarizedField>
        <summaryFilterItems>
            <field>Answer__c.Selected__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Question__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_Correct_Answers__c</fullName>
        <description>Total number of correct answers.</description>
        <label>Number of Correct Answers</label>
        <summaryFilterItems>
            <field>Answer__c.Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Question__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <description>The question number indicates the order in which to display the questions in an examination.  This field is not used for exam template questions.</description>
        <label>Question Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>This is the body which makes up a question.</description>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ExaminationsController.cls
public without sharing class ExaminationsController {

	private final Examination__c exam;
	public Integer actualQuestion {
		get {
			if (actualQuestion == null)
				actualQuestion = 0;
			return actualQuestion;
		}
		set;
	}
	public List<QuestionAnswerWrapper> questionAnswerWrapperList {
		get {
			if (questionAnswerWrapperList == null)
				questionAnswerWrapperList = new List<QuestionAnswerWrapper>();
			return questionAnswerWrapperList;
		}
		set;
	}
	public QuestionAnswerWrapper questionWrapper {
		get {
			if (questionCount >= actualQuestion && actualQuestion > 0) {
				return questionAnswerWrapperList[actualQuestion - 1];
			}
			return questionWrapper;
		}
		set;
	}
	public Integer questionCount {get;set;}
	public Boolean isEmpty {get;set;}
	public Boolean isReview {get;set;}
	
	public ExaminationsController (ApexPages.StandardController stdController) {
		
		exam = (Examination__c) stdController.getRecord();
		//actualQuestion = 0;
		List<Question__c> questions = [Select 
						Question__c, 
						Question_Number__c,
						Number_of_Correct_Answers__c,
						Number_Correctly_Selected__c,
						Mark_For_Review__c,
						(Select
							Number__c,
							Selected__c,
							Answer__c
						 from Answers__r
						 order by Number__c asc
						)
					 from Question__c
					 where Examination__c = :exam.Id
					 order by Question_Number__c asc
					];
		questionCount = questions.size();
		if (questionCount == 0)
			isEmpty = true;
		else
			fillWrapperList(questions);
	}
	
	public void fillWrapperList (List<Question__c> questions) {
		for (Question__c quest : questions) {
			questionAnswerWrapperList.add(new QuestionAnswerWrapper(quest));
		}
	}
	
	public void start() {
		exam.Examination_Status__c = 'In Progress';
		update exam;
		actualQuestion = 1;
	}
	
	public void onLoad () {
		if (exam.Examination_Status__c != 'New' && actualQuestion == 0) {
			actualQuestion = 1;
		}
	}
	
	public void next() {
		try {
			validateSelected();
			//Should I or Shouldn't I save the answers???
			update questionWrapper.getAnswers();
			update questionWrapper.question;
			actualQuestion += 1;
		}
		catch (InvalidNumberSelectedException ex) {
			ApexPages.addMessages(ex);
		}
		catch (Exception exc) {
			ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.FATAL,'Please contact your administrator, an unexpected error has occurred');
			ApexPages.addMessage(message);
		}
	}
	
	public void previous() {
		try {
			validateSelected();
			update questionWrapper.getAnswers();
			update questionWrapper.question;
			actualQuestion -= 1;
		}
		catch (InvalidNumberSelectedException ex) {
			ApexPages.addMessages(ex);
		}
		catch (Exception exc) {
			ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.FATAL,'Please contact your administrator, an unexpected error has occurred');
			ApexPages.addMessage(message);
		}
	}
	
	public void review() {
		try {
			validateSelected();
			update questionWrapper.getAnswers();
			update questionWrapper.question;
			isReview = true;
		}
		catch (InvalidNumberSelectedException ex) {
			ApexPages.addMessages(ex);
		}
		catch (Exception exc) {
			ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.FATAL,'Please contact your administrator, an unexpected error has occurred');
			ApexPages.addMessage(message);
		}
	}
	
	public void goToQuestion() {
		isReview = false;
	}
	
	public void validateSelected() {
		if (questionWrapper.getSelectedAnswers().size() != questionWrapper.question.Number_of_Correct_Answers__c) 
			throw new InvalidNumberSelectedException('Please select ' + questionWrapper.question.Number_of_Correct_Answers__c + ' answer(s)');
	}
	
	public class InvalidNumberSelectedException extends Exception {}
}