src/objects/Examination__c.object
<CustomObject>
    <description>An examination is essentially an instance of a test for an exam taker.  When a new examination is created, it contains a copy of all the questions from the test form that make up the test.  Examinations may be performed in practice mode.</description>
    <fields>
        <fullName>Examination_Status__c</fullName>
        <description>The examination status indicates whether an examination is New, In Progress, or Completed.</description>
        <label>Examination Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Test_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The test form field indicates the test form that this examination was created from.</description>
        <label>Test Form</label>
        <referenceTo>Test_Form__c</referenceTo>
        <relationshipLabel>Examinations</relationshipLabel>
        <relationshipName>Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <label>Examination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>A question may be related to either a test form or an examination.  Test form questions are used as templates when creating examination questions.</description>
    <fields>
        <fullName>Correct__c</fullName>
        <description>Checks to see if the number of correctly selected answers equals the number of correct answers.</description>
        <formula>IF(Number_Correctly_Selected__c == Number_of_Correct_Answers__c,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Correct</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The examination field indicates the examination that this question belongs to.</description>
        <label>Examination</label>
        <referenceTo>Examination__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Correct_Answers__c</fullName>
        <description>Total number of correct answers.</description>
        <label>Number of Correct Answers</label>
        <summaryFilterItems>
            <field>Answer__c.Correct__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Answer__c.Question__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>This is the body which makes up a question.</description>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Test_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The test form field indicates the test form that this question belongs to.</description>
        <label>Test Form</label>
        <referenceTo>Test_Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Test_Form__c.object
<CustomObject>
    <description>The test form is used to store information about a test.  It contains a description as well as summary information.  Test forms are created and managed by an exam administrator.</description>
    <fields>
        <fullName>Passing_Score__c</fullName>
        <defaultValue>0.70</defaultValue>
        <description>The passing score for this exam.</description>
        <label>Passing Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Test Form</label>
    <nameField>
        <label>Test Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Commons.cls
public without sharing class Commons {
	
	//Exception declaration
	public class InvalidNumberSelectedException extends Exception {}
	public class InvalidQuestionException extends Exception {}
	public class LimitationException extends Exception {}
	
	//Method that calculates the score of the exam or Test form and returns a wrapper class with the result
	public static resultClass calculateResult(sObject exam) {
		Integer correctAnswers = 0;
		Integer totalQuestions = 0;
		//Requery to make sure it's the last snapshot of the examination or Test Form
		
		String soqlQuery = 'Select (Select Correct__c from Questions__r),';
		Double passPercent;
		
		//Query Examinations
		if (exam.getsObjectType() == Examination__c.sObjectType) {
			soqlQuery += ' Test_Form__r.Passing_Score__c from Examination__c ';
			soqlQuery += ' where Id = \'' + exam.Id + '\'';
			Examination__c examination = Database.query(soqlQuery);
			examination.Examination_Status__c = 'Completed';
			passPercent = examination.Test_Form__r.Passing_Score__c;
			totalQuestions = examination.Questions__r.size();
			correctAnswers = getCorrectAnswers(examination.Questions__r);
		}
		
		//Query Test Forms
		if (exam.getsObjectType() == Test_Form__c.sObjectType) {
			soqlQuery += ' Passing_Score__c from Test_Form__c ';
			soqlQuery += ' where Id = \'' + exam.Id + '\'';
			Test_Form__c test_form = Database.query(soqlQuery);
			passPercent = test_form.Passing_Score__c;
			totalQuestions = test_form.Questions__r.size();
			correctAnswers = getCorrectAnswers(test_form.Questions__r);
		}
		
		//Calculate and return score		
		Double actualPercent = Double.valueOf(correctAnswers) / Double.valueOf(totalQuestions) * 100.0;
		
		return (new resultClass(actualPercent >= passPercent, correctAnswers));
	}
	
	//Method that returns the number of questions correctly answered
	private static Integer getCorrectAnswers (List<Question__c> questions) {
		Integer correctAnswers = 0;
		for(Question__c question : questions) {
			if (question.Correct__c == 1) {
				correctAnswers ++;
			}
		}
		return correctAnswers;
	}
	
	//Method that validates that the number of selected answers is the same as the number of correct answers
	private static void validateSelected(QuestionAnswerWrapper questionWrapper) {
		if (questionWrapper.getSelectedAnswers().size() != questionWrapper.question.Number_of_Correct_Answers__c) 
			throw new Commons.InvalidNumberSelectedException('Please select ' + questionWrapper.question.Number_of_Correct_Answers__c + ' answer(s)');
	}
	
	//Methos that populates a QuestionAnswer Wrapper list to handle exams and Test Forms
	public static List<QuestionAnswerWrapper> fillWrapperList (List<Question__c> questions) {
		List<QuestionAnswerWrapper> questionAnswerWrapperList = new List<QuestionAnswerWrapper>();
		
		for (Question__c quest : questions) {
			questionAnswerWrapperList.add(new QuestionAnswerWrapper(quest));
		}
		
		return questionAnswerWrapperList;
	}
	
	//Method that handles the action of pushing the next button
	public static Integer next(QuestionAnswerWrapper questionWrapper, Integer actualQuestion) {
		updateQuestion(questionWrapper);
		return actualQuestion + 1;
	}
	
	//Method that handles the action of pushing the previous button
	public static Integer previous(QuestionAnswerWrapper questionWrapper, Integer actualQuestion) {
		updateQuestion(questionWrapper);
		return actualQuestion - 1;
	}
	
	//Method that handles the action of pushing the review button
	public static Boolean review(QuestionAnswerWrapper questionWrapper) {
		updateQuestion(questionWrapper);
		return true;
	}
	
	//Method that updates the question, this is done in every action, I decided to do it this way to give the user the ability to exit and come back later and still have his answers.
	private static void updateQuestion(QuestionAnswerWrapper questionWrapper) {
		validateSelected(questionWrapper);
		update questionWrapper.getAnswers();
		update questionWrapper.question;
	}
	
	//Wrapper class for the result, with a boolean value and the number of questions correctly answered
	public class resultClass {
		public Boolean pass {get;set;}
		public Integer correctAnswers {get;set;}
		
		public resultClass (Boolean p, Integer cA) {
			pass = p;
			correctAnswers = cA;
		}
	}

}