src/objects/Examination__c.object
<CustomObject>
    <description>An examination is essentially an instance of a test for an exam taker.  When a new examination is created, it contains a copy of all the questions from the test form that make up the test.  Examinations may be performed in practice mode.</description>
    <fields>
        <fullName>Examination_Taker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The examination taker field indicates the person taking the examination.</description>
        <label>Examination Taker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Examinations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The test form field indicates the test form that this examination was created from.</description>
        <label>Test Form</label>
        <referenceTo>Test_Form__c</referenceTo>
        <relationshipLabel>Examinations</relationshipLabel>
        <relationshipName>Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <label>Examination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Test_Form__c.object
<CustomObject>
    <description>The test form is used to store information about a test.  It contains a description as well as summary information.  Test forms are created and managed by an exam administrator.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Exam Templates, and therefore Examinations are specific to the Accounts that they are for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Exam_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Status__c</fullName>
        <description>The test status field indicates whether a test is Draft, Open (available to take), Closed, or Obsolete.</description>
        <label>Test Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Test Form</label>
    <nameField>
        <label>Test Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>This field is used to store the ID of the Account that a Test Taker belongs to. Test Takers can only take Examinations that are available for their Account.</description>
        <label>Account ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestFormsAvailable.cls
public with sharing class TestFormsAvailable {
	
	public List<TestFormAvailable> testFormsAvailable {get;set;}
	
	private static final String adminProfileName = 'Custom: Exam Administrator';
	private static final String takerProfileName = 'Custom: Exam Taker';
	private static final String draftStatusString = 'Draft';
	private static final String openStatusString = 'Open';
	
	public TestFormsAvailable () {
		
		testFormsAvailable = new List<TestFormAvailable>();

		fillAvailableForms(Userinfo.getUserId());
	}
	
	private void fillAvailableForms (Id userId) {
		
		
		List<Test_Form__c> userTestForms = new List<Test_Form__c>();
		userTestForms = [Select Name from Test_Form__c where Test_Status__c = :draftStatusString];

		/*
		User userProfile = [Select Profile.Name, Account_Id__c from User where Id = :userId limit 1];
		
		if (userProfile.Profile.Name == adminProfileName) {
			userTestForms = [Select Name from Test_Form__c where Test_Status__c = :draftStatusString];
		}
		
		if (userProfile.Profile.Name == takerProfileName) {
			userTestForms = [Select Id,Name from Test_Form__c where Account__c = :userProfile.Account_Id__c and Test_Status__c = :openStatusString];
		}
		*/
		
		Map<Id,Test_Form__c> testFormsMap = getFormsMap(userTestForms);
		
		List<Examination__c> userExaminations = [Select Name,Test_Form__c from Examination__c where Test_Form__c in :testFormsMap.keyset() and Examination_Taker__c = :userId];
		
		TestFormAvailable testAvailable = new TestFormAvailable();
		
		for (Examination__c exam : userExaminations) {
			testAvailable = new TestFormAvailable();
			testAvailable.examinationCreated = true;
			testAvailable.testForm = testFormsMap.get(exam.Test_Form__c);
			testFormsAvailable.add(testAvailable);
			testFormsMap.remove(exam.Test_Form__c);
		}
		
		for (Id key : testFormsMap.keyset()) {
			testAvailable = new TestFormAvailable();
			testAvailable.examinationCreated = false;
			testAvailable.testForm = testFormsMap.get(key);
			testFormsAvailable.add(testAvailable);
		}
	}
	
	private Map<Id,Test_Form__c> getFormsMap(List<Test_Form__c> forms) {
		Map<Id,Test_Form__c> testFormsMap = new Map<Id,Test_Form__c>();
		for (Test_Form__c testForm : forms) {
				testFormsMap.put(testForm.Id, testForm);
		}
		
		return testFormsMap;
	}

	public class TestFormAvailable {
		public Test_Form__c testForm {get;set;}
		public Boolean examinationCreated {get;set;} 
	}
}