src/objects/Examination__c.object
<CustomObject>
    <description>An examination is essentially an instance of a test for an exam taker.  When a new examination is created, it contains a copy of all the questions from the test form that make up the test.  Examinations may be performed in practice mode.</description>
    <fields>
        <fullName>Test_Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The test form field indicates the test form that this examination was created from.</description>
        <label>Test Form</label>
        <referenceTo>Test_Form__c</referenceTo>
        <relationshipLabel>Examinations</relationshipLabel>
        <relationshipName>Examinations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Examination</label>
    <nameField>
        <label>Examination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Examinations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>A question may be related to either a test form or an examination.  Test form questions are used as templates when creating examination questions.</description>
    <fields>
        <fullName>Examination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The examination field indicates the examination that this question belongs to.</description>
        <label>Examination</label>
        <referenceTo>Examination__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>This is the body which makes up a question.</description>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Test_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The test form field indicates the test form that this question belongs to.</description>
        <label>Test Form</label>
        <referenceTo>Test_Form__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Test_Form__c.object
<CustomObject>
    <description>The test form is used to store information about a test.  It contains a description as well as summary information.  Test forms are created and managed by an exam administrator.</description>
    <label>Test Form</label>
    <nameField>
        <label>Test Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CommonsTest.cls
/**
 * 
 */
@isTest
private class CommonsTest {
	
    static testMethod void test_Commons_calculateResult_TestForms_Pass() {
        Test_Form__c testForm = TestUtilities.createTestForm(true);
        
        List<User> admins = TestUtilities.getExamAdminUsers(1);
        insert admins;
        
        System.runAs(admins[0]) {
	        Test.startTest();
	        
	        Commons.resultClass result = Commons.calculateResult(testform);
	        
	        Test.stopTest();
	        
	        System.assertEquals(result.correctAnswers, TestUtilities.numberOfQuestions);
	        System.assert(result.pass);
        }
    }
    
    static testMethod void test_Commons_calculateResult_TestForms_Fail() {
        Test_Form__c testForm = TestUtilities.createTestForm(false);
		
		List<User> admins = TestUtilities.getExamAdminUsers(1);
        insert admins;
        
        System.runAs(admins[0]) {
	        Test.startTest();
	        
	        Commons.resultClass result = Commons.calculateResult(testform);
	        
	        Test.stopTest();
	        
	        System.assertEquals(result.correctAnswers, 0);
	        System.assert(!result.pass);
        }
    }
    
    static testMethod void test_Commons_calculateResult_Examinations_Pass() {
        
        List<User> takers = TestUtilities.getExamTakerUsers(1);
        insert takers;
        
        Examination__c examination = TestUtilities.createExamination(takers[0], true);
        
        System.runAs(takers[0]) {
	        Test.startTest();
	        
	        Commons.resultClass result = Commons.calculateResult(examination);
	        
	        Test.stopTest();
	        
	        System.assertEquals(result.correctAnswers, TestUtilities.numberOfQuestions);
	        System.assert(result.pass);
        }
    }
    
    static testMethod void test_Commons_calculateResult_Examinations_Fail() {
        List<User> takers = TestUtilities.getExamTakerUsers(1);
        insert takers;
        
        Examination__c examination = TestUtilities.createExamination(takers[0], false);
        
        System.runAs(takers[0]) {
	        Test.startTest();
	        
	        Commons.resultClass result = Commons.calculateResult(examination);
	        
	        Test.stopTest();
	        
	        System.assertEquals(result.correctAnswers, 0);
	        System.assert(!result.pass);
        }
    }
    
    static testMethod void test_Commons_next() {
							 
        QuestionAnswerWrapper questionWrapper = TestUtilities.createCorrectQuestion();
        Integer actualQuestion = 1;
        
        List<User> admins = TestUtilities.getExamAdminUsers(1);
        insert admins;
        
        System.runAs(admins[0]) {
	        Test.startTest();
	        
	        Integer result = Commons.next(questionWrapper, actualQuestion);
	        
	        Test.stopTest();
	        
	        System.assertEquals(result,2);
        }
    }
    
    static testMethod void test_Commons_next_Exception() {
        QuestionAnswerWrapper questionWrapper = TestUtilities.createWrongQuestion();
        Integer actualQuestion = 1;
        Integer result;
        
        List<User> admins = TestUtilities.getExamAdminUsers(1);
        insert admins;
        
        System.runAs(admins[0]) {
	        Test.startTest();
	        
	        try {
	        	result = Commons.next(questionWrapper, actualQuestion);
	        }
	        catch (Commons.InvalidNumberSelectedException invEx) {
	        	result = 9999;
	        }
	        
	        Test.stopTest();
	        
	        System.assertEquals(result,9999);
        }
    }
    
    static testMethod void test_Commons_previous() {
        QuestionAnswerWrapper questionWrapper = TestUtilities.createCorrectQuestion();
        Integer actualQuestion = 2;
        
        List<User> admins = TestUtilities.getExamAdminUsers(1);
        insert admins;
        
        System.runAs(admins[0]) {
        	
	        Test.startTest();
	        
	        Integer result = Commons.previous(questionWrapper, actualQuestion);
	        
	        Test.stopTest();
	        
	        System.assertEquals(result,1);
        }
    }
    
    static testMethod void test_Commons_previous_Exception() {
		QuestionAnswerWrapper questionWrapper = TestUtilities.createWrongQuestion();
        Integer actualQuestion = 2;
        Integer result;
        
        List<User> admins = TestUtilities.getExamAdminUsers(1);
        insert admins;
        
        System.runAs(admins[0]) {
	        Test.startTest();
	        
	        try {
	        	result = Commons.previous(questionWrapper, actualQuestion);
	        }
	        catch (Commons.InvalidNumberSelectedException invEx) {
	        	result = 9999;
	        }
	        
	        Test.stopTest();
	        
	        System.assertEquals(result,9999);
        }
    }
    
    static testMethod void test_Commons_review() {
        QuestionAnswerWrapper questionWrapper = TestUtilities.createCorrectQuestion();
        Integer actualQuestion = 1;
        
        List<User> admins = TestUtilities.getExamAdminUsers(1);
        insert admins;
        
        System.runAs(admins[0]) {
	        Test.startTest();
	        
	        Boolean result = Commons.review(questionWrapper);
	        
	        Test.stopTest();
	        
	        System.assert(result);
        }
    }
    
    static testMethod void test_Commons_review_Exception() {
        QuestionAnswerWrapper questionWrapper = TestUtilities.createWrongQuestion();

        Boolean result;
        
        List<User> admins = TestUtilities.getExamAdminUsers(1);
        insert admins;
        
        System.runAs(admins[0]) {
	        Test.startTest();
	        
	        try {
	        	result = Commons.review(questionWrapper);
	        }
	        catch (Commons.InvalidNumberSelectedException invEx) {
	        	result = false;
	        }
	        
	        Test.stopTest();
	        
	        System.assert(!result);
        }
    }
    
    static testMethod void test_Commons_fillWrapperList() {
        List<Account> accounts = TestUtilities.createAccounts(1);
        insert accounts;
        List<Test_Form__c> testForms = TestUtilities.createTestForms(1, accounts[0].Id, 'Draft');
        insert testforms;
        List<Question__c> questions = TestUtilities.createQuestions(TestUtilities.numberOfQuestions, testForms[0].Id, true);
        insert questions;
        
        Test.startTest();
        
        List<QuestionAnswerWrapper> questionWrapperList = Commons.fillWrapperList(questions);
                
        Test.stopTest();
        
        System.assertEquals(questionWrapperList.size(),questions.size());
    }
    
    static testMethod void test_Commons_fillWrapperList_Empty() {
        
        List<Question__c> questions = new List<Question__c>();
        insert questions;
        
        Test.startTest();
        
        List<QuestionAnswerWrapper> questionWrapperList = Commons.fillWrapperList(questions);
                
        Test.stopTest();
        
        System.assertEquals(questionWrapperList.size(),0);
    }
}